---
id: rwc-2014
base_name: distributed-full-text-search-middleware-in-ruby
tags:
- rabbit
- ruby
- rwc2014
presentation_date: 2014-11-13
version: 2014.11.13.6
licenses:
- CC BY-SA 4.0
slideshare_id: rwc-2014
speaker_deck_id: rubywoshi-tutafen-san-quan-wen-jian-suo-midoruuea
ustream_id: 
vimeo_id: 
youtube_id: 
author:
  markup_language: :rd
  name: Kouhei Sutou
  email: kou@clear-code.com
  rubygems_user: kou
  slideshare_user: kou
  speaker_deck_user: kou
